# Generated by Django 4.2.2 on 2023-07-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_rom_laptops_laptopmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptops',
            name='Description',
            field=models.TextField(),
        ),
    ]
